### ISSUE TITLE
[Documentation] Create drawio ER Modell

### ISSUE THREAD

**Issue by Quadral1403** [SMABFWS121A/Planty#5]
**Is your feature request related to a problem? Please describe.**
Currently, we have not documented the relationships and generally the objects anywhere.

**Describe the solution you'd like**
An ER model is used to record which objects exist and how they relate to each other. This helps in understanding the whole structure.

**Comment by Kitt3120** [comment]
No description 😡

**Comment by Kryschtzyk** [comment]
FUCK YOU @Quadral1403

**Comment by Kitt3120** [comment]
Gelbe Karte @Kryschtzyk
