### ISSUE TITLE
[Feature/Developer] Implement frontend

### ISSUE THREAD

**Issue by Quadral1403** [SMABFWS121A/Planty#9]
1. Implement Frontend
2. connect to classes generated by openapi

**Comment by Kryschtzyk** [comment]
Ich würde das Ticket hier in mehrere Tickets untergliedern.

**Comment by Kitt3120** [comment]
Sehe ich auch so, sind 2 unterschiedliche Tickets. Das Frontend kannst du schon so "implementieren", also schon mal anfangen, bisschen aufsetzen, Grundgerüst aufbauen. Das mit der OpenAPI kommt danach, das müssen wir ja auch noch mal bisschen besprechen.

**Comment by Kryschtzyk** [comment]
Ich würde es so gliedern, dass bspw. 
setup frontend envrionment ein ticket wäre
openapi ist sowieso ein anderes
Und dann für jedes Frontend feature ein issue.
Bspw. create diagramms in frontend usw.
